apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tandin-deploy
  name: tandin-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tandin-deploy
  template:
    metadata:
      labels:
        app: tandin-deploy
    spec:
      containers:
      - image: tandin18/takin:34
        name: pet
