apiVersion: v1
kind: Service
metadata:
  labels:
    app: tandin-deploy
  name: tandin-svc
  #namespace: pet
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tandin-deploy
  type: NodePort
